### PR TITLE
Fix for issue #78

### PR DESCRIPTION
**Pull request by skjolber**
See issue #78 - the z position is set to an incorrect value.

### CODE REVIEW

**Comment by skjolber** [comment]
@balachandarsv does this look good to you?

**Comment by balachandarsv** [comment]
Thanks @skjolber.

For C,
Space top = new Space(freespace.getWidth(), freespace.getDepth() - used.getWidth(), freespace.getHeight(),freespace.getX(), freespace.getY() ~~+ used.getWidth()~~, freespace.getZ());
For D, 
Space rightRemainder = new Space(used.getDepth(), freespace.getDepth() - used.getWidth(), freespace.getHeight(),freespace.getX(), freespace.getY() ~~+ used.getWidth()~~, freespace.getZ());

I guess the above values provide proper results. 

Here is a diff of the results from your code and my code for the spaces available at C and D,
https://quickdiff.net/?unique_id=83C344FB-8553-5D0F-CD5A-A4725175320B

**Comment by balachandarsv** [comment]
@skjolber  Did you check the free space calculation issue I mentioned above?

**Comment by skjolber** [comment]
@balachandarsv yes, but it had low readability. The z coorfinate must always be propagated, so that was fixed..

**Pull request merged**
