### PR TITLE
test: BruteForce does not honor a deadline

### PR DESCRIPTION
**Pull request by tyrcho**
I found that on this problem the deadline is not respected and the packager never returns

### CODE REVIEW

**Comment by tyrcho** [comment]
Note : this problem is solved with PlainPackager. The actual issue is that I run both implementations in parallel, and FastBruteForce is expected to timeout properly.

**Comment by tyrcho** [comment]
@skjolber I discovered something interesting. 

When given a short deadline (50-200ms on my computer) FastBruteForce properly "gives up" and returns null after the deadline.

However with a longer deadline (1-2 sec for me), it gets stuck and never gives up.

**Comment by skjolber** [comment]
Thanks for the bug report, I'll look into it. The packager tries not to get the current time all the time (as a performance enhancement), probably something there.

**Comment by tyrcho** [comment]
FWIW, on average, `System.currentTimeMillis` can be run at least 6k-10k times per millisec on my computer, it seems to have a negligible impact when I run it in a loop of 1 000 000 iterations.

**Comment by skjolber** [comment]
It is iterator.nextRotation(..) that is stuck without a deadline check. I'll add a fix, as we can jump directly to the correct rotation.

**Comment by skjolber** [comment]
@tyrcho I've improved the "jump to rotation" / "jump to permutation" logic, however with 93 boxes, the brute force packager just does not complete. The method for removing shadowed points does not scale all that well, but a solution is not straightforward, so I suggest capping the use of the brute force packager and adding more heuristics is the best overall approach.

**Comment by skjolber** [comment]
@see latest (for now unreleased) master for the improvements.

**Comment by skjolber** [comment]
Try the 2.1.0 release

**Pull request closed without merging**
