### PR TITLE
simple javafx visu

### PR DESCRIPTION
**Pull request by arminhaaf**
I implemented a simpe JavaFX Visualization, if you are interested, just integrate it...

### CODE REVIEW

**Comment by arminhaaf** [comment]
added a step by step viewer, which show the algorithm by render each placement and the calculated free spaces step by step -> it helped me a lot to understand the algorithm

**Comment by skjolber** [comment]
@arminhaaf looks very interesting. I am about to merge a bit change into the master branch, so perhaps hold your horses a little bit.

**Comment by arminhaaf** [comment]
also added simple bag semantics -> instead using a fixed sized box, a bag may change its dimensions
a simple solution for bags could be to change the dimensions for first product and after first level is done -> see the code

**Comment by arminhaaf** [comment]
Bag semantics seems to work now, had some problems to find the correct places to adapt the bag size...

**Comment by skjolber** [comment]
@arminhaaf very interesting with the bag logic. The recent v2.x release is a major improvement, do you think you'd be able to migrate the code?

**Comment by arminhaaf** [comment]
@skjolber its hard to understand the changes in version 2.0. Maybe you can explain the ideas behind the changes.

I would like to migrate the visualization also...

I need the following code position for simple bag semantics
- selection of the first item for the target container -> bag has special semantics here
- switch to the next level -> to adapt the bag to the size of the first level

for the visualisation a callback would be good (this is the callback interface i introduced in version 1:

public interface PackCallback {

	default void freeSpacesCalculated(List<Space> pFreeSpaces) {
	}

	default void placementAdded(Placement pPlacement) {
	}

	default void levelAdded(Container pContainer, long pNewLevel) {
	}

	default void packDone() {
	}

}

for me its hard to find the relevant code positions in the new version without some help...

**Pull request closed without merging**
