### PR TITLE
 test for LAFF with about 20 products

### PR DESCRIPTION
**Pull request by tyrcho**
This packaging has a solution (found by https://www.3dbinpacking.com/en/)
but the LAFF is pretty far, only 6 boxes are packed

image

Any idea how we can better results (ie more boxes packed) ?

### CODE REVIEW

**Comment by tyrcho** [comment]
I think I found an interesting approach here ... maybe trying the 6 different rotations makes sense inside the LAFF implementation, what do you think @skjolber  ?

**Comment by skjolber** [comment]
I guess there is a reason those guys are still in business :) 

But yeah, the LAFF is really happy-go-lucky. 

I think the 2D-placement logic should be done in 3D instead and there should be multiple ways of 'scoring' the placement of the next box and/or the free remaining free space - combined with a healthy dose of 'lets try everything we can within the allocated time'.

**Comment by tyrcho** [comment]
have you seen my other comments on #14 ? I'm actually quite happy with the implementation of the new branch ! When trying different rotations and combining with BruteForce I got similar results to the paying API on several real world, complex use cases.

**Comment by tyrcho** [comment]
well, it's pretty easy to rotate the container, compared to rotating all boxes ...

**Pull request merged**
