### PR TITLE
Parallel brute force packager

### PR DESCRIPTION
**Pull request by skjolber**
Parallel per permutations.

### CODE REVIEW

**Comment by skjolber** [comment]
This improvement needs better performance test cases.

**Comment by skjolber** [comment]
@tyrcho do you guys have some performance test-cases to share?

**Comment by tyrcho** [comment]
hi, we are in the middle of updating our software which uses this lib :)
I'll share some cases next week when at work.

**Comment by tyrcho** [comment]
22 packets in 1500, 1900, 4000

```scala
 Packet(590, 1085, 305),
      Packet(20, 1010, 10),
      Packet(20, 1010, 10),
      Packet(100, 1050, 750),
      Packet(80, 650, 2150),
      Packet(475, 330, 40),
      Packet(91, 500, 720),
      Packet(95, 650, 760),
      Packet(100, 850, 760),
      Packet(30, 620, 10),
      Packet(30, 620, 10),
      Packet(90, 210, 680),
      Packet(100, 650, 750),
      Packet(100, 450, 750),
      Packet(100, 450, 750),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(16, 2500, 11),
      Packet(47, 3010, 660),
      Packet(47, 3010, 660),
      Packet(47, 3010, 660),
      Packet(1000, 1000, 1000),
      Packet(1000, 1000, 1000),
      Packet(1120, 420, 70),
      Packet(215, 585, 355),
      Packet(685, 490, 870),
      Packet(600, 678, 118),
      Packet(670, 635, 654),
      Packet(570, 570, 1840),
      Packet(1000, 1000, 1000),
      Packet(91, 500, 720),
      Packet(215, 585, 355)
```

**Comment by tyrcho** [comment]
33 in 1500, 1900, 4000

```scala
 Packet(56, 1001, 1505),
      Packet(360, 1100, 120),
      Packet(210, 210, 250),
      Packet(210, 210, 250),
      Packet(70, 70, 120),
      Packet(50, 80, 80),
      Packet(20, 20, 500),
      Packet(50, 230, 50),
      Packet(40, 40, 50),
      Packet(50, 50, 60),
      Packet(1000, 32, 32),
      Packet(2000, 40, 40),
      Packet(40, 40, 60),
      Packet(60, 90, 40),
      Packet(56, 40, 20),
      Packet(100, 280, 380),
      Packet(2500, 600, 80),
      Packet(125, 125, 85),
      Packet(80, 180, 360),
      Packet(25, 140, 140),
      Packet(115, 150, 170),
      Packet(76, 76, 222),
      Packet(326, 326, 249),
      Packet(70, 130, 240),
      Packet(330, 120, 490),
      Packet(9, 23, 2500),
      Packet(2000, 20, 20),
      Packet(50, 50, 235),
      Packet(1000, 1000, 1000),
      Packet(30, 66, 230),
      Packet(30, 66, 230),
      Packet(1000, 1000, 1000),
      Packet(90, 610, 210),
      Packet(144, 630, 1530)
```

**Comment by tyrcho** [comment]
93 packets (same container again)

```scala
Packet(1170, 510, 200),
      Packet(300, 250, 70),
      Packet(100, 850, 750),
      Packet(720, 420, 78),
      Packet(720, 420, 78),
      Packet(920, 720, 110),
      Packet(530, 120, 570),
      Packet(470, 550, 190),
      Packet(470, 550, 190),
      Packet(75, 650, 1600),
      Packet(620, 160, 27),
      Packet(80, 650, 2150),
      Packet(2020, 620, 32),
      Packet(100, 850, 760),
      Packet(720, 420, 30),
      Packet(720, 420, 30),
      Packet(95, 650, 760),
      Packet(720, 660, 20),
      Packet(720, 660, 20),
      Packet(2020, 660, 20),
      Packet(2020, 660, 20),
      Packet(535, 110, 500),
      Packet(720, 620, 78),
      Packet(280, 800, 480),
      Packet(100, 1050, 750),
      Packet(720, 150, 22),
      Packet(720, 520, 30),
      Packet(89, 950, 750),
      Packet(89, 950, 750),
      Packet(89, 950, 750),
      Packet(720, 460, 33),
      Packet(720, 460, 33),
      Packet(720, 460, 33),
      Packet(720, 460, 33),
      Packet(100, 650, 750),
      Packet(100, 650, 750),
      Packet(720, 620, 30),
      Packet(720, 620, 30),
      Packet(720, 620, 30),
      Packet(720, 620, 30),
      Packet(55, 500, 745),
      Packet(55, 500, 745),
      Packet(720, 170, 30),
      Packet(720, 170, 30),
      Packet(53, 360, 950),
      Packet(53, 360, 950),
      Packet(136, 30, 140),
      Packet(136, 30, 140),
      Packet(920, 370, 36),
      Packet(920, 370, 36),
      Packet(950, 380, 20),
      Packet(950, 380, 20),
      Packet(950, 380, 20),
      Packet(950, 380, 20),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(40, 100, 165),
      Packet(47, 3010, 660),
      Packet(47, 3010, 660),
      Packet(16, 2500, 11),
      Packet(16, 2500, 11),
      Packet(16, 2500, 11),
      Packet(16, 2500, 11),
      Packet(2720, 150, 20),
      Packet(2720, 150, 20),
      Packet(2720, 150, 20),
      Packet(2720, 150, 20),
      Packet(2720, 150, 20),
      Packet(475, 830, 40),
      Packet(680, 585, 145),
      Packet(680, 635, 864),
      Packet(100, 100, 850),
      Packet(1000, 1000, 1000),
      Packet(60, 25, 560),
      Packet(60, 25, 560),
      Packet(120, 80, 45),
      Packet(60, 120, 200),
      Packet(50, 50, 230),
      Packet(50, 50, 230),
      Packet(18, 18, 2400),
      Packet(1000, 1000, 1000),
      Packet(1000, 1000, 1000),
      Packet(300, 200, 30),
      Packet(300, 200, 30),
      Packet(300, 200, 30),
      Packet(300, 200, 30),
      Packet(300, 200, 30),
      Packet(47, 3010, 660)
```

**Comment by tyrcho** [comment]
And this is another JMH test you can take inspiration from.

Basically  it generates l x w x h small boxes of size 155 x 288 x 342 (+ a small delta) and tries to pack them in a large enough container

l x w x h goes from 1x1x1 to 3x2x4 but you can easily add larger cases.

```scala
package com.colisweb.binpacking.benchmark
import java.util.concurrent.TimeUnit

import com.colisweb.binpacking.Types.NonEmptyList
import com.colisweb.binpacking._
import com.colisweb.binpacking.utils.monix.PureLogger
import eu.timepit.refined.refineV
import eu.timepit.refined.types.numeric.PosInt
import org.openjdk.jmh.annotations._
import play.api.Logger

import scala.concurrent.duration.DurationInt

@Warmup(iterations = 10, time = 2000, timeUnit = TimeUnit.MILLISECONDS)
@Measurement(iterations = 10, time = 2000, timeUnit = TimeUnit.MILLISECONDS)
@Fork(1)
@BenchmarkMode(Array(Mode.Throughput, Mode.AverageTime))
@OutputTimeUnit(TimeUnit.MILLISECONDS)
class PackerBenchmark {

  import monix.execution.Scheduler.Implicits.global

  @Benchmark
  def packerBench(state: PackerBenchState): List[(Packaging, GroupedContainers)] = {
    import state._

    packer
      .pack(packets, largeEnoughContainer)
      .runSyncUnsafe(10.seconds)
  }

}

@State(Scope.Thread)
class PackerBenchState {
  import com.colisweb.binpacking.utils.refined.RichPosInt._

  @Param(Array("1", "3"))
  var lengthCount: Int = _

  @Param(Array("1", "2"))
  var widthCount: Int = _

  @Param(Array("1", "4"))
  var heightCount: Int = _

  var packer: Packer = _

  var packets: NonEmptyList[Packet] = _

  var largeEnoughContainer: NonEmptyList[GroupedContainers] = _

  @Setup
  def setup(): Unit = {
    packer = new PackerImpl(new PureLogger(Logger("tests")))
    val length: PosInt = refineV.unsafeFrom(155)
    val width: PosInt  = refineV.unsafeFrom(288)
    val height: PosInt = refineV.unsafeFrom(342)

    def packet(i: Int) = Packet(
      length = length + i,
      width = width + i,
      height = height + i
    )
    val packetsCount = lengthCount * widthCount * heightCount
    packets = refineV.unsafeFrom(List.tabulate(packetsCount)(packet))
    largeEnoughContainer = refineV.unsafeFrom(
      GroupedContainers(
        names = ContainerName("parallelepiped") :: Nil,
        length = (length + packetsCount) * lengthCount * 2,
        width = (width + packetsCount) * widthCount * 2,
        height = (height + packetsCount) * heightCount * 2
      ) :: Nil
    )
  }
}

```

**Comment by tyrcho** [comment]
here is an overview of the current performance on these benchmarks : http://jmh.morethan.io/?source=https://colisweb.gitlab.io/3d-packing-api/packing.json

**Comment by skjolber** [comment]
@tyrcho thanks! I have decided to refactor the project structure into a multimodule project with a JMH module, as I have preexisting code to copy.

**Comment by skjolber** [comment]
Merged but pending release

**Pull request merged**
