### PR TITLE
test packing several identical boxes in just-fitting containers

### PR DESCRIPTION
**Pull request by tyrcho**
another PBT for when you fixed the previous bug.

We probably need to tune down the amount of boxes this tries to brute-force pack, 1000 (even if identical) is probably too ambitious ...

### CODE REVIEW

**Comment by skjolber** [comment]
It is possible to calculate the number (cost) of operations needed for some particular operation. All identical boxes will essentially mean all rotations.

**Comment by tyrcho** [comment]
only 8 identical boxes ? I'm quite surprised, in the released versions I'm quite sure it could handle at least 30 identical boxes in less than 1 second. This timing was what I had with this amount of different boxes.

**Comment by skjolber** [comment]
Well that depends on the number of rotations available I guess. Perhaps the new code is slower than the old.

**Comment by tyrcho** [comment]
would you like some help with JMH setup to measure the performance of the key methods ? we just set it up in our project

**Comment by skjolber** [comment]
@tyrcho sure, but perhaps as a seperate project? Does your setup resemble some of the JMH projects I already have - like https://github.com/skjolber/csv-benchmark? I guess a seperate project is the most easy..

**Comment by tyrcho** [comment]
well now that I've seen your csv-benchmark project, I know you are much more advanced on jmh than I am :)
I think I can help better in other areas, like PBT for instance !

**Pull request merged**
