### PR TITLE
Simple visualization tool for #69

### PR DESCRIPTION
**Pull request by dazito**
Added Gson dependency as the json parser
Container class can be parsed to json and the parsed json can be saved into a file. This file is then imported by the visualization tool and the boxes are drawn in a 2D canvas.

Class ContainerModel is a simple POJO class that holds all information regarding a specific container.
Class PlacementModel is a simple POJO class that holds the information about where a given box is to be placed in the container.

The webapp is an Angular app.
There are two pages: 2D and 3D. 
Currently, only the 2D pages is fully functional. A canvas is presented and when the json file is imported the canvas takes the size of the container and the boxes are drawn inside the canvas.
The canvas assumes the top left corner as having the coordinate 0,0 (x,y). On the canvas, from up down the value of Y is incrementing and always positive while the value of X from left to right is incrementing and always positive.

Example:
```
(0,0) => (x,y)
------------------- (10,0)
|
|
|
|          .
|        (5,5)
|
|
(0, 10)
```

### CODE REVIEW

**Comment by dazito** [comment]
Codacy is failing due to Javascript using a single quote (') instead of double quote (")
Travis CI seems to not be related with my PR. Could you clear this out?

**Comment by skjolber** [comment]
@dazito updated travis build in master, better?

**Comment by dazito** [comment]
@skjolber yup, looks good

**Comment by skjolber** [comment]
Thank you very much for your effort, here is some initial feedback:

 * The Space / Box / Placement / Level would be very valuable to include in the visualization, because they tell a lot about how the algorithm works and which decitions were made. So that would imply that the JSON structure directly reflects the current objects. I guess Level could be interpreted as 'step' or 'pass' or something like that, to make it more generic. Although I'd agree that algorithm analyzis and packaging instructions are two seperate use-cases, I'd like to support them both (perhaps with a button to toggle in-between?). 

 * JSON generation would be better in seperate classes, so that dependencies like GSON can be made optional. Rather than recreating DTO objects, it would be possible to transform or adjust the objects on the fly and in a streaming fashion  using for example Jackson to write the actual JSON; like in https://www.baeldung.com/jackson-streaming-api. As seperate maven module for the visualizer is also an option (basically the project is now multi-moduled, with the addition of the visualizer). 

 * No unit tests for convertion to JSON
 * Visualizer only accepts .txt files, what about .json files?
 * Not really able to get the vizualization working? Is there any good existing example json input file?
 * Linking an input file via an url parameter would be very practical

**Comment by dazito** [comment]
Thanks for the feedback.
I will address two points now, the remaining ones I will address later when I have more free time.

_Visualizer only accepts .txt files, what about .json files?_
No, it should accept any file extension as long as it has valid json inside. I guess I should rename that string to make it more clear.

Here's a json example that I kept around when I was testing:
{"placement":[{"name":"Foot","x":0,"y":0,"z":0,"width":60,"length":100,"height":20},{"name":"Leg","x":60,"y":0,"z":0,"width":40,"length":100,"height":10},{"name":"Arm","x":0,"y":100,"z":0,"width":40,"length":100,"height":20}],"weight":1000,"width":300,"length":300,"height":300,"volume":27000000}

**Pull request closed without merging**
