### PR TITLE
Improve support calculation

### PR DESCRIPTION
**Pull request by skjolber**
See issue #663

So two problems:

 * box is only placed at extreme point origins, does not account for support found in the plane of the extreme point
 * the support area must be compared to the increase in z placement

### CODE REVIEW

**Comment by khorchanov** [comment]
Did a very quick test and seems this does not solve the issue 
Seems just prefer stacking same boxes aligned one on other with same rotation, which is not better that what we had before
image

And we have always the floating boxes (not new to this PR) : 
image

**Comment by skjolber** [comment]
Yeah this is not going to be much better before the extreme point implementation is extended. Basically gravity is not taken into account now, the extreme points implementation is not sufficiently flexible to let the packager take the right decition.

**Comment by khorchanov** [comment]
I think we have two problems here :
- The story of stacking vertically, I'd suggest in the `isBetter` prefer the minimum Z over the support
```java
	protected boolean isBetter(Stackable referenceStackable, Point3D<StackPlacement> referencePoint, StackValue referenceStackValue, Stackable candidateBox, Point3D<StackPlacement> candidatePoint,
			StackValue candidateStackValue) {
		// ********************************************
		// * Prefer lowest point
		// ********************************************

		if(candidatePoint.getMinZ() == referencePoint.getMinZ()) {

			// compare supported area
			long referenceSupport = referencePoint.calculateXYSupport(referenceStackValue.getDx(), referenceStackValue.getDy());
			long candidateSupport = candidatePoint.calculateXYSupport(candidateStackValue.getDx(), candidateStackValue.getDy());

			if (candidateSupport == referenceSupport) {

				if(candidateStackValue.getArea() == referenceStackValue.getArea()) {

					// compare sideways support	
					referenceSupport = referencePoint.calculateXZSupport(referenceStackValue.getDx(), referenceStackValue.getDz()) +
							referencePoint.calculateYZSupport(referenceStackValue.getDy(), referenceStackValue.getDz());

					candidateSupport = candidatePoint.calculateXZSupport(candidateStackValue.getDx(), candidateStackValue.getDz()) +
							candidatePoint.calculateYZSupport(candidateStackValue.getDy(), candidateStackValue.getDz());

					if(candidateSupport == referenceSupport) {
						// if everything is equal, the point with the tightest fit 
						return candidatePoint.getArea() < referencePoint.getArea();
					}
					return candidateSupport > referenceSupport;
				}
				return candidateStackValue.getArea() > referenceStackValue.getArea();

			}
			return candidateSupport > referenceSupport;
		}
		return candidatePoint.getMinZ() < referencePoint.getMinZ();
	}
```
In my test that does a great job in stacking horizontally across the container then vertically.

- The problem with floating boxes, I really don't understand the mean of ExtremePoints in this project, but in my debugging, when stacking that (floating) one it seems that the Point3D is a `DefaultXZPlaneYZPlanePoint3D` so no XY support.
I mean if we can like calculate the support surface of the box, if it is less that 60% of the bottom surface then do not accept this stacking value (refuse it as it is a constraint)

**Comment by skjolber** [comment]
@khorchanov did some adjustments, got the following:

image

What do you think?

**Comment by skjolber** [comment]
The free floating issue cannot be solved with the current implementation

**Comment by khorchanov** [comment]
@skjolber Seems to be very smooth, nice work !
But yea the floating boxes is a real issue, I don't know if we can implement a simple workaround in the meanwhile ? Like refuse to stack when supported surface is less than a % of the box's bottom surface ?

**Comment by Gu00-pikapika** [comment]
> @skjolber Seems to be very smooth, nice work ! But yea the floating boxes is a real issue, I don't know if we can implement a simple workaround in the meanwhile ? Like refuse to stack when supported surface is less than a % of the box's bottom surface ?

你好，我做了这种尝试，我在pack代码中加入了，`								if (point3d.getMinZ() != 0 && pointSupportPercent < 100 - 50) {
									continue;
								}`  bestPointSupportPercent等于100时，表示其需要百分百的支撑，但是我不知是否会有其他bug

**Pull request merged**
